### ISSUE TITLE
denite support

### ISSUE THREAD

**Issue by emiasims** [chemzqm/unite-location#1]
Hi, would you consider supporting [denite](https://github.com/Shougo/denite.nvim)?

**Comment by chemzqm** [comment]
Sure, I heard that denite could just make use of unite source, and I will rewrite my unite sources to python remote plugin when I figured out how to do that.

**Comment by emiasims** [comment]
Shougo's [neomru](https://github.com/Shougo/neomru.vim/blob/master/rplugin/python3/denite/source/file_mru.py) plugin seems to be a simple example (at least for a naive implementation), as well as the [line source](https://github.com/Shougo/denite.nvim/blob/master/rplugin/python3/denite/source/line.py) from base. I don't understand the parsing or the formats of returned values, though. If I figure it out (again, the simple implementation, I'm new to writing plugins) I'll pass it along to you.

**Comment by chemzqm** [comment]
@mtszyk I have implemented it.

**Comment by emiasims** [comment]
That's awesome, you're awesome! I'll open a new issue if I come across any bugs.
