### ISSUE TITLE
Change qf filetype color

### ISSUE THREAD

**Issue by petobens** [chemzqm/unite-location#4]
Hi @chemzqm I was wondering how to do two things. Currently when I run `Denite quickfix` or `Unite quickfix` on the ouput (for instance) of fugitive's `Glog % --` I see the following output:
![screen shot 2017-02-04 at 13 51 26](https://cloud.githubusercontent.com/assets/2583971/22620041/975db4f6-eae1-11e6-99c6-539485d60cc1.png)

I would like to:
i) change how the filenames are highlighted: i.e I would like to use the `Directory` hl group for this.
ii) If there is no column or line number indication then I would like to avoid showing it (currently it is displayed as `0 col 0`). 
Essentially the desired output is:
![screen shot 2017-02-04 at 13 51 59](https://cloud.githubusercontent.com/assets/2583971/22620046/9cceba52-eae1-11e6-87c4-99b931387e9d.png)

Is this possible? Thanks in advance

**Comment by chemzqm** [comment]
It is possible, but I would consider it over complexcity since it's not suitable for quickfix list to represent git log.
May be you would like to try out https://github.com/chemzqm/unite-git-log, it has much better interface and has support for extra actions, like: diff，preview, reset.
I use that plugin quite a lot.

**Comment by petobens** [comment]
@chemzqm thanks for your kind reply. My question was about how can I change the filename highlight group (I just posted a Git log as an example). I want the filename to be highlighted as a `Directory`.  The following is a screenshot were I don't use Git log:
![screen shot 2017-02-05 at 11 15 38](https://cloud.githubusercontent.com/assets/2583971/22626802/a6c1a192-eb94-11e6-90aa-6199e0658abd.png)

Can this be done?

Regarding my second request I believe that when there are no line or column numbers you should not display `0` [here](https://github.com/chemzqm/unite-location/blob/master/rplugin/python3/denite/source/quickfix.py#L35) but rather `''`.

Once again thanks!

**Comment by chemzqm** [comment]
OK, I can understand.
One way is you can pass extra args like `Unite quickfix:gitlog` so the function `s:source.hooks.on_syntax` could check the `a:args[0] == gitlog` to react the highlight accordingly.
